{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "139edce2-5cfe-4d95-8bbd-be51e705ef4b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Overwriting app.py\n"
     ]
    }
   ],
   "source": [
    "%%writefile app.py\n",
    "\n",
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import plotly.graph_objects as go\n",
    "from plotly.subplots import make_subplots\n",
    "import ta\n",
    "\n",
    "st.set_page_config(page_title=\"NSE Stock Technical Analysis App\", layout=\"wide\")\n",
    "\n",
    "st.title(\"📈 NSE Stock Data & Technical Analysis Dashboard\")\n",
    "st.markdown(\"Upload any raw stock data file (CSV, XLS, XLSX) from the NSE website. The app will automatically parse dates, prices, and volumes.\")\n",
    "\n",
    "# Sidebar for file upload supporting multiple formats\n",
    "st.sidebar.header(\"Upload Data\")\n",
    "uploaded_file = st.sidebar.file_uploader(\"Upload NSE File\", type=[\"csv\", \"xlsx\", \"xls\"])\n",
    "\n",
    "# Function to generate sample data if none uploaded\n",
    "@st.cache_data\n",
    "def load_default_data():\n",
    "    dates = pd.date_range(end=pd.Timestamp.today(), periods=250, freq='B')\n",
    "    np.random.seed(42)\n",
    "    prices = 100 + np.cumsum(np.random.randn(250) * 1.5)\n",
    "    df = pd.DataFrame({\n",
    "        'Date': dates,\n",
    "        'Open': prices + np.random.randn(250) * 0.5,\n",
    "        'High': prices + abs(np.random.randn(250) * 1.5),\n",
    "        'Low': prices - abs(np.random.randn(250) * 1.5),\n",
    "        'Close': prices + np.random.randn(250) * 0.5,\n",
    "        'Volume': np.random.randint(100000, 5000000, size=250)\n",
    "    })\n",
    "    return df\n",
    "\n",
    "# Universal parser for raw NSE files\n",
    "def parse_raw_file(file):\n",
    "    try:\n",
    "        # Check file extension to read correctly\n",
    "        if file.name.endswith('.csv'):\n",
    "            df = pd.read_csv(file)\n",
    "        elif file.name.endswith(('.xls', '.xlsx')):\n",
    "            df = pd.read_excel(file)\n",
    "        else:\n",
    "            return None, \"Unsupported file format.\"\n",
    "\n",
    "        # Strip whitespace from column names\n",
    "        df.columns = df.columns.str.strip()\n",
    "        \n",
    "        # Map common variations found in NSE raw files\n",
    "        col_mapping = {}\n",
    "        for col in df.columns:\n",
    "            c_upper = col.upper()\n",
    "            if any(k in c_upper for k in ['DATE', 'TIMESTAMP', 'TRADDT']):\n",
    "                col_mapping[col] = 'Date'\n",
    "            elif c_upper in ['OPEN', 'OPEN_PRICE', 'OPENPRC']:\n",
    "                col_mapping[col] = 'Open'\n",
    "            elif c_upper in ['HIGH', 'HIGH_PRICE', 'HIGHPRC']:\n",
    "                col_mapping[col] = 'High'\n",
    "            elif c_upper in ['LOW', 'LOW_PRICE', 'LOWPRC']:\n",
    "                col_mapping[col] = 'Low'\n",
    "            elif c_upper in ['CLOSE', 'CLOSE_PRICE', 'CLOSEPRC']:\n",
    "                col_mapping[col] = 'Close'\n",
    "            elif c_upper in ['TOTTRDQTY', 'VOLUME', 'TTL_TRD_QNTY', 'QTY', 'TRADED_QTY']:\n",
    "                col_mapping[col] = 'Volume'\n",
    "                \n",
    "        df = df.rename(columns=col_mapping)\n",
    "        \n",
    "        required_cols = ['Date', 'Open', 'High', 'Low', 'Close', 'Volume']\n",
    "        if not all(col in df.columns for col in required_cols):\n",
    "            return None, f\"Could not automatically map columns. Found columns: {list(df.columns)}. Ensure the file contains Date, Open, High, Low, Close, and Volume equivalents.\"\n",
    "\n",
    "        # Clean Dates\n",
    "        df['Date'] = pd.to_datetime(df['Date'], errors='coerce')\n",
    "        \n",
    "        # Clean Numeric columns (remove commas if formatted as strings like \"1,234.50\")\n",
    "        for col in ['Open', 'High', 'Low', 'Close', 'Volume']:\n",
    "            if df[col].dtype == object:\n",
    "                df[col] = df[col].astype(str).str.replace(',', '').str.strip()\n",
    "            df[col] = pd.to_numeric(df[col], errors='coerce')\n",
    "            \n",
    "        df = df.dropna(subset=['Date', 'Close']).sort_values('Date').reset_index(drop=True)\n",
    "        return df, None\n",
    "    except Exception as e:\n",
    "        return None, str(e)\n",
    "\n",
    "if uploaded_file is not None:\n",
    "    df, error_msg = parse_raw_file(uploaded_file)\n",
    "    if error_msg:\n",
    "        st.error(f\"Error parsing file: {error_msg}\")\n",
    "        df = load_default_data()\n",
    "    else:\n",
    "        st.sidebar.success(\"NSE File successfully processed!\")\n",
    "else:\n",
    "    st.sidebar.info(\"Using sample stock data. Upload an NSE file (CSV/Excel) to test.\")\n",
    "    df = load_default_data()\n",
    "\n",
    "# --- CALCULATE TECHNICAL INDICATORS ---\n",
    "df['SMA_20'] = ta.trend.sma_indicator(df['Close'], window=20)\n",
    "df['SMA_50'] = ta.trend.sma_indicator(df['Close'], window=50)\n",
    "df['RSI'] = ta.momentum.rsi(df['Close'], window=14)\n",
    "\n",
    "macd = ta.trend.MACD(df['Close'])\n",
    "df['MACD'] = macd.macd()\n",
    "df['MACD_signal'] = macd.macd_signal()\n",
    "df['MACD_diff'] = macd.macd_diff()\n",
    "\n",
    "bollinger = ta.volatility.BollingerBands(df['Close'], window=20, window_dev=2)\n",
    "df['BB_High'] = bollinger.bollinger_hband()\n",
    "df['BB_Low'] = bollinger.bollinger_lband()\n",
    "df['BB_Mid'] = bollinger.bollinger_mavg()\n",
    "\n",
    "# --- TABS FOR ORGANIZING CHARTS ---\n",
    "tab1, tab2, tab3 = st.tabs([\"📊 Financial & Technical Charts\", \"📉 General Statistical Plots\", \"📋 Raw Data\"])\n",
    "\n",
    "with tab1:\n",
    "    st.subheader(\"Core Technical Analysis Indicators\")\n",
    "    \n",
    "    # 1 & 5. Candlestick + Bollinger Bands\n",
    "    st.markdown(\"### 1 & 5. Candlestick Chart with Bollinger Bands & Moving Averages\")\n",
    "    fig_candle = make_subplots(rows=2, cols=1, shared_xaxes=True, vertical_spacing=0.03, row_heights=[0.7, 0.3])\n",
    "    fig_candle.add_trace(go.Candlestick(x=df['Date'], open=df['Open'], high=df['High'], low=df['Low'], close=df['Close'], name='Candlestick'), row=1, col=1)\n",
    "    fig_candle.add_trace(go.Scatter(x=df['Date'], y=df['SMA_20'], line=dict(color='orange', width=1.5), name='SMA 20'), row=1, col=1)\n",
    "    fig_candle.add_trace(go.Scatter(x=df['Date'], y=df['SMA_50'], line=dict(color='blue', width=1.5), name='SMA 50'), row=1, col=1)\n",
    "    fig_candle.add_trace(go.Scatter(x=df['Date'], y=df['BB_High'], line=dict(color='gray', dash='dash', width=1), name='BB High'), row=1, col=1)\n",
    "    fig_candle.add_trace(go.Scatter(x=df['Date'], y=df['BB_Low'], line=dict(color='gray', dash='dash', width=1), name='BB Low', fill='tonexty'), row=1, col=1)\n",
    "    fig_candle.add_trace(go.Bar(x=df['Date'], y=df['Volume'], name='Volume', marker_color='purple'), row=2, col=1)\n",
    "    fig_candle.update_layout(height=600, xaxis_rangeslider_visible=False, template='plotly_dark')\n",
    "    st.plotly_chart(fig_candle, use_container_width=True)\n",
    "\n",
    "    # 3. RSI\n",
    "    st.markdown(\"### 3. Relative Strength Index (RSI)\")\n",
    "    fig_rsi = go.Figure()\n",
    "    fig_rsi.add_trace(go.Scatter(x=df['Date'], y=df['RSI'], line=dict(color='magenta', width=2), name='RSI'))\n",
    "    fig_rsi.add_hline(y=70, line_dash=\"dash\", line_color=\"red\")\n",
    "    fig_rsi.add_hline(y=30, line_dash=\"dash\", line_color=\"green\")\n",
    "    fig_rsi.update_layout(height=300, yaxis_range=[0, 100], template='plotly_dark', margin=dict(t=20, b=20))\n",
    "    st.plotly_chart(fig_rsi, use_container_width=True)\n",
    "\n",
    "    # 4. MACD\n",
    "    st.markdown(\"### 4. Moving Average Convergence & Divergence (MACD)\")\n",
    "    fig_macd = go.Figure()\n",
    "    fig_macd.add_trace(go.Scatter(x=df['Date'], y=df['MACD'], line=dict(color='cyan', width=1.5), name='MACD'))\n",
    "    fig_macd.add_trace(go.Scatter(x=df['Date'], y=df['MACD_signal'], line=dict(color='orange', width=1.5), name='Signal'))\n",
    "    fig_macd.add_trace(go.Bar(x=df['Date'], y=df['MACD_diff'], name='Histogram', marker_color='gray'))\n",
    "    fig_macd.update_layout(height=300, template='plotly_dark', margin=dict(t=20, b=20))\n",
    "    st.plotly_chart(fig_macd, use_container_width=True)\n",
    "\n",
    "with tab2:\n",
    "    st.subheader(\"Statistical Plots & Alternative Views\")\n",
    "    col1, col2 = st.columns(2)\n",
    "    \n",
    "    with col1:\n",
    "        # 6. Line Chart\n",
    "        st.markdown(\"### 6. Closing Price Line Chart\")\n",
    "        fig_line = go.Figure(go.Scatter(x=df['Date'], y=df['Close'], mode='lines', line=dict(color='lime')))\n",
    "        fig_line.update_layout(height=350, template='plotly_dark')\n",
    "        st.plotly_chart(fig_line, use_container_width=True)\n",
    "\n",
    "        # 7. Bar Chart\n",
    "        st.markdown(\"### 7. Trading Volume Bar Chart\")\n",
    "        fig_bar = go.Figure(go.Bar(x=df['Date'], y=df['Volume'], marker_color='dodgerblue'))\n",
    "        fig_bar.update_layout(height=350, template='plotly_dark')\n",
    "        st.plotly_chart(fig_bar, use_container_width=True)\n",
    "\n",
    "        # 9. Histogram\n",
    "        st.markdown(\"### 9. Histogram of Close Prices\")\n",
    "        fig_hist = go.Figure(go.Histogram(x=df['Close'], nbinsx=20, marker_color='teal'))\n",
    "        fig_hist.update_layout(height=350, template='plotly_dark')\n",
    "        st.plotly_chart(fig_hist, use_container_width=True)\n",
    "\n",
    "    with col2:\n",
    "        # 12. Area Chart\n",
    "        df['Cumulative_Return'] = (1 + df['Close'].pct_change()).cumprod() - 1\n",
    "        st.markdown(\"### 12. Cumulative Return Area Chart\")\n",
    "        fig_area = go.Figure(go.Scatter(x=df['Date'], y=df['Cumulative_Return'], fill='tozeroy', line=dict(color='gold')))\n",
    "        fig_area.update_layout(height=350, template='plotly_dark')\n",
    "        st.plotly_chart(fig_area, use_container_width=True)\n",
    "\n",
    "        # 10. Box Plot\n",
    "        st.markdown(\"### 10. Box Plot of OHLC Prices\")\n",
    "        fig_box = go.Figure()\n",
    "        for col in ['Open', 'High', 'Low', 'Close']:\n",
    "            fig_box.add_trace(go.Box(y=df[col], name=col))\n",
    "        fig_box.update_layout(height=350, template='plotly_dark')\n",
    "        st.plotly_chart(fig_box, use_container_width=True)\n",
    "\n",
    "        # 11. Scatter Plot\n",
    "        st.markdown(\"### 11. Scatter Plot: Volume vs. Close Price\")\n",
    "        fig_scatter = go.Figure(go.Scatter(x=df['Volume'], y=df['Close'], mode='markers', marker=dict(color=df['Close'], colorscale='Viridis', showscale=True)))\n",
    "        fig_scatter.update_layout(height=350, template='plotly_dark')\n",
    "        st.plotly_chart(fig_scatter, use_container_width=True)\n",
    "\n",
    "    col3, col4 = st.columns(2)\n",
    "    with col3:\n",
    "        # 8. Pie Chart\n",
    "        df['Month'] = df['Date'].dt.strftime('%B %Y')\n",
    "        monthly_vol = df.groupby('Month')['Volume'].sum().reset_index()\n",
    "        st.markdown(\"### 8. Pie Chart: Volume Distribution by Month\")\n",
    "        fig_pie = go.Figure(go.Pie(labels=monthly_vol['Month'], values=monthly_vol['Volume'], hole=.3))\n",
    "        fig_pie.update_layout(height=400, template='plotly_dark')\n",
    "        st.plotly_chart(fig_pie, use_container_width=True)\n",
    "\n",
    "    with col4:\n",
    "        # 13. Stacked Bar Chart\n",
    "        monthly_hl = df.groupby('Month')[['High', 'Low']].sum().reset_index()\n",
    "        st.markdown(\"### 13. Stacked Bar Chart: Monthly High/Low Totals\")\n",
    "        fig_stacked = go.Figure()\n",
    "        fig_stacked.add_trace(go.Bar(x=monthly_hl['Month'], y=monthly_hl['High'], name='Total High', marker_color='indianred'))\n",
    "        fig_stacked.add_trace(go.Bar(x=monthly_hl['Month'], y=monthly_hl['Low'], name='Total Low', marker_color='royalblue'))\n",
    "        fig_stacked.update_layout(barmode='stack', height=400, template='plotly_dark')\n",
    "        st.plotly_chart(fig_stacked, use_container_width=True)\n",
    "\n",
    "with tab3:\n",
    "    st.subheader(\"Cleaned Dataset View\")\n",
    "    st.dataframe(df, use_container_width=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e65ec162-ab59-48f5-9e17-e069a1f52f46",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "661b5f8a-fa01-429f-ac14-7fe848d9509b",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.14.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
